version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: java@
    ports:
      - 3306:3306
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8888