version: "3.7"

services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: "SeuEmail@SeuEmail.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"
        volumes:
            - pgadmin:/var/lib/pgadmin

    postgres:
        restart: always
        image: postgres:11-alpine
        container_name: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "base"
        volumes:
            - pgvol:/var/lib/postgresql/data
volumes:
    pgvol:
    pgadmin: 